channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - adapterremoval=2.3.1
  - argcomplete=1.12.1
  - argparse=1.4.0
  - biopython=1.77
  - bowtie2=2.3.5.1
  - dedup=0.12.5
  - numpy=1.19.2
  - pandas=1.0.3
  - pip=19.3.1
  - psutil=5.7.2
  - pysam=0.16.1
  - python=3.6.7
  - pyyaml=5.3.1
  - r-rcpp=1.0.4.6
  - r-rcppgsl=0.3.8
  - r-gam=1.16.1
  - r-ggplot2=3.3.0
  - r-inline=0.3.15
  - requests=2.24.0
  - rsync=3.1.3
  - samtools=1.9
  - scipy=1.4.1
  - seqkit=0.13.2
  - seqtk=1.3
  - setuptools=49.6.0
  - snakefmt=0.2.4
  - snakemake=5.26.1
  - sra-tools=2.10.1
  - wget=1.20.1
  - mapdamage2=2.2.1
  - picard=2.24.0
