query_name:
  refseq_rep
entrez_query:
  ("Yersinia"[Organism] OR "Yersinia"[Organism]) AND "complete genome"[All Fields]
entrez_email:
  evangelos-antonios.dimopoulos@hertford.ox.ac.uk
entrez_batchsize:
  5
entrez_rank:
  'species'

sample_name:
  ''
sample_fastq:
  []
sample_fastq_R1:
  []
sample_fastq_R2:
  []

mismatch_probability:
  0.05

bowtie2_treads:
  1

SRA_LOOKUP:
  True
PE_ANCIENT:
  False
PE_MODERN:
  True
SE:
  False

WITH_REFSEQ_REP:
  True
WITH_ENTREZ_QUERY:
  True

SPECIFIC_GENUS:
  []

MEM_RESOURCES_MB:
  80
MEM_RESCALING_FACTOR:
  2.5

WITH_DATA_PREPROCESSING:
  True

WITH_CUSTOM_SEQUENCES:
  False
custom_seq_file:
  custom_seq.txt

WITH_CUSTOM_ACCESSIONS:
  False
custom_acc_file:
  custom_acc.txt

