#entrez:
#  queries:
#    # query to send to NCBI for retrieving the species tp
#    refseq_rep: ("Yersinia"[Organism] OR "Yersinia"[Organism]) AND "complete genome"[All Fields]
#
#  # email used to identify the user making an Entrez request
#  email: evangelos-antonios.dimopoulos@hertford.ox.ac.uk
#
#  # fetch results in batches
#  batchSize: 5
#
#  rank: 'species'


#samples:
#  CSL.all: fastq_inputs/CSL.all.fastq.gz
#
#  RISE00: [fastq_inputs/RISE00_rmdup.fastq.gz]
#
#  SRR1031215:
#    R1: [sra_data/SRR1031215_R1.fastq.gz]
#    R2: [sra_data/SRR1031215_R2.fastq.gz]
#
#  SRR055002:
#    sra_data/SRR055002.fastq.gz

query_name:
  refseq_rep
entrez_query:
  ("Yersinia"[Organism] OR "Yersinia"[Organism]) AND "complete genome"[All Fields]
entrez_email:
  evangelos-antonios.dimopoulos@hertford.ox.ac.uk
entrez_batchsize:
  5
entrez_rank:
  'species'

sample_name:
  SRR1031215
sample_fastq:
  sra_data/SRR1031215.fastq.gz
sample_fastq_R1:
  [sra_data/PE/SRR1031215_R1.fastq.gz]
sample_fastq_R2:
  [sra_data/PE/SRR1031215_R2.fastq.gz]

min_mapq:
  20
mismatch_probability:
  0.05
sequencing:
  'single_end'

bowtie2_treads:
  1

SRA_LOOKUP:
  False
PE_ANCIENT:
  False
PE_MODERN:
  True
SE:
  False

WITH_REFSEQ_REP:
  True
WITH_ENTREZ_QUERY:
  True

SPECIFIC_GENUS:
#  ['Yersinia']
  []

MEM_RESOURCES_MB:
  80
MEM_RESCALING_FACTOR:
  2.5

WITH_DATA_PREPROCESSING:
  True