channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.7
  - snakemake=5.12.3
  - pysam=0.15.3
  - biopython=1.76
  - bowtie2=2.3.5.1
  - samtools=1.9
  - dedup=0.12.5
  - scipy=1.4.1
  - seqtk=1.3
  - wget
  - adapterremoval=2.3.1
  - sra-tools=2.9.1
  - mapdamage2
R:
  - inline
  - gam
  - RcppGSL
