package:
  name: haystack
  version: 0.1

source:
  git_rev:
  git_url: https://github.com/antonisdim/rip

requirements:
  build:
    - python
    - setuptools

  depends:
    - argparse
    - argcomplete
    - snakemake 
    - biopython

  run:
    - python

test:
  imports:
    -

about:
  home:
