package:
  name: haystack
  version: 0.1

source:
  git_rev:
  git_url: https://github.com/antonisdim/haystack.git

build:
  - script: python -m pip install --upgrade --no-deps --force-reinstall .

requirements:
  build:
    - python
    - setuptools
  
  run:
    - python 
    - argcomplete
    - argparse
    - biopython
    - numpy
    - pandas
    - psutil
    - pysam
    - pyyaml
    - requests
    - scipy
    - setuptools
    - snakemake

test:
  imports:
    -

about:
  home: https://github.com/antonisdim/haystack.git
  license: MIT
  summary: New metagenomics pipeline 
