# `haystack config` defaults
cache:
  ~/haystack/cache/
clear_cache:
  False
batchsize:
  5
mismatch_probability:
  0.05
bowtie2_threads:
  15
bowtie2_scaling:
  5.0
use_conda:
  True

# `haystack database` defaults
rank:
  'species'
seed:
  null
cores:
  all
mem:
  all

# `haystack sample` defaults
collapse:
  False
trim_adapters:
  True
read_probability_threshold:
  0.75