# `haystack config` defaults
cache:
  ~/haystack/cache/
mismatch_probability:
  0.05
bowtie2_scaling:
  25.0
use_conda:
  True

# `haystack database` defaults
rank:
  'species'
seed:
  null
cores:
  all
mem:
  all

# `haystack sample` defaults
collapse:
  False
trim_adapters:
  True
min_prob:
  0.75