# haystack config defaults

cache:
  ~/haystack/cache/
batchsize:
  5
mismatch_probability:
  0.05
bowtie2_threads:
  15
use_conda:
  True



rank:
  'species'
bowtie2_scaling:
  5
dry_run:
  False
db_output:
  None
refseq_rep:
  False
mtDNA:
  False
query:
  None
query_file:
  None
sequences:
  ""
accessions:
  ""
genera: []
sample_prefix:
  ""
sample_output_dir:
  ""
fastq:
  None
fastq_r1:
  None
fastq_r2:
  None
sra:
  None
collapse:
  False
trim_adapters:
  True
adaperremoval_flags:
  ""
database:
  None
sample:
  None
analysis_output_dir:
  None
read_probability_threshold:
  0.75
seed:
  1
unlock:
  False
debug:
  False
snakemake:
