# `haystack config` defaults
cache:
  ~/haystack/cache/
batchsize:
  5
mismatch_probability:
  0.05
bowtie2_threads:
  15
bowtie2_scaling:
  5
use_conda:
  True

# `haystack database` defaults
mode:
  build
rank:
  'species'
seed:
  null
cores:
  all
mem:
  all

# `haystack sample` defaults
collapse:
  False
trim_adapters:
  True

#sample_prefix:
#  ""
#sample_output_dir:
#  ""
#fastq:
#  None
#fastq_r1:
#  None
#fastq_r2:
#  None
#sra:
#  None
#collapse:
#  False
#adaperremoval_flags:
#  ""
#database:
#  None
#sample:
#  None
#analysis_output_dir:
#  None
#read_probability_threshold:
#  0.75
#
#unlock:
#  False
#debug:
#  False
#snakemake:
